# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
	"bootstrap",
    "downgrade",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
	"linux-zen",
    "preload",
    "linux-zen-headers",
    "nvidia-dkms",
    "lib32-nvidia-utils",
    "lib32-opencl-nvidia",
    "libva-nvidia-driver",
    "linux-firmware-nvidia",
    "nvidia-settings",
    "nvidia-utils",
    "opencl-nvidia",
    "hyprland",
    "cairo",
    "aquamarine",
    "libaquamarine.so",
    "gcc-libs",
    "glibc",
    "glib2",
    "libgio-2.0.so",
    "libgobject-2.0.so",
    "glslang",
    "hyprcursor",
    "libhyprcursor.so",
    "hyprgraphics",
    "libhyprgraphics.so",
    "hyprland-qtutils",
    "hyprlang",
    "libhyprlang.so",
    "hyprutils",
    "libhyprutils.so",
    "hyprwayland-scanner",
    "libdisplay-info",
    "libdisplay-info.so",
    "libdrm",
    "libglvnd",
    "libEGL.so",
    "libGLESv2.so",
    "libOpenGL.so",
    "libinput",
    "libliftoff",
    "libliftoff.so",
    "libx11",
    "libxcb",
    "libxcomposite",
    "libxcursor",
    "libxfixes",
    "libxkbcommon",
    "libxkbcommon.so",
    "libxrender",
    "mesa",
    "lib32-mesa",
    "opengl-driver",
    "pango",
    "libpango-1.0.so",
    "libpangocairo-1.0.so",
    "pixman",
    "libpixman-1.so",
    "re2",
    "libre2.so",
    "seatd",
    "libseat.so",
    "systemd-libs",
    "libsystemd.so",
    "tomlplusplus",
    "libtomlplusplus.so",
    "libudev.so",
    "util-linux-libs",
    "libuuid.so",
    "wayland",
    "libwayland-client.so",
    "libwayland-server.so",
    "wayland-protocols",
    "xcb-proto",
    "xcb-util",
    "xcb-util-errors",
    "xcb-util-image",
    "xcb-util-keysyms",
    "xcb-util-renderutil",
    "xcb-util-wm",
    "xorg-xwayland",

    # Optional dependencies (bez wersji, bo brak podanych)
    "perl",
    "cmake",
    "cpio",
    "glaze",
    "hyprland-protocols",
    "meson",
    "ttf-meslo-nerd",
    "noto-fonts",
    "ghostty",
    "pipewire",
    "pipewire-jack",
    "pipewire-pulse",
    "pipewire-alsa",
    "wireplumber",
    "qpwgraph",
    "pavucontrol",
    "zen-browser-bin",
    "nemo",
    "gvfs-smb",
    "fastfetch",
    "imagemagick",
    "fish",
    "hyprsunset",
    "oh-my-posh-bin",
    "steam",
    "gamescope",
    "waybar",
    "socat",
    "jq",
    "swww",
    "full-dracula-theme-git",
    "sweet-folders-icons-git",
    "bibata-cursor-theme-bin",
    "hyprshot",
    "wl-clip-persist",
    "wl-clipboard",
    "xdg-desktop-portal-hyprland",
    "ntfs-3g",
    "obs-studio-git",
    "obs-multi-rtmp --noconfirm",
    "vesktop-bin",
    "ayugram-desktop-bin",
    "rofi-wayland",
    "visual-studio-code-bin",
    "inotify-tools",
    "timeshift",
    "nano",
    "micro",
    "nvim",
    "nano-syntax-highlighting",
    "curl",
    "wget",
    "swayimg",
    "mako",
    "hypridle",
    "hyprlock",
    "wlogout --noconfirm",
    "github-cli",
    "winetricks",
    "yabridge",
    "yabridgectl",
    "kvantum",
    "qt6",
    "libvirt",
    "virt-manager",
    "virt-viewer",
    "qemu-full",
    "vde2",
    "ebtables",
    "iptables-nft",
    "nftables",
    "bridge-utils",
    "ovmf",
    "swtpm",
    "dnsmasq",
    "btop",
    "mpv",
    "freerdp2",
    "heroic-games-launcher-bin",
    "unityhub --noconfirm",
    "locate",
    "dconf-editor",
    "nemo-fileroller",
    "p7zip-full-bin",
    "freedownloadmanager",
    "unrar",
    "cpupower",
    "unigine-valley",
    "curseforge",
    "spotify --noconfirm",
    "reflector",
    "ufw",
    "gimp",
    "libportal",
    "drawing",
    "gcc",
    "clang",
    "portaudio",
    "davinci-resolve-studio",
    "rustup",
    "pw-lat",
    "mingw-w64-gcc",
    "dbus-glib",
    "webkit2gtk",
    "webkit2gtk-4.1",
    "create-tauri-app ",
    "bun-bin",
    "gnome-disk-utility",
    "irqbalance",
    "stow",
]


# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
    #"flathub fm.reaper.Reaper"
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
